/**
 * Shared types for the recommendation rules engine (US 3).
 *
 * The engine is rules-driven and deterministic. Each rule consumes the
 * `RecommendationContext`, produces a structured contribution (eligibility
 * filter / score basis / exclusion / impact / roadmap bucketing), and
 * enumerates the signals it consulted (FR-113 traceability).
 *
 * Bedrock-enriched explanations are layered on top of these structures by
 * `audit/workers/ai.worker.ts` when `BEDROCK_ENABLED=true`. The shape of
 * `EngineOutput` is the same in both modes.
 */

import type { ScoreDimension, ScenarioKind } from "@/db/schema/recommendation";

export const RULE_ENGINE_VERSION = "rules-v1.0.0";

/* ------------------------------ Context ------------------------------ */

/**
 * The vendor catalogue is supplied to the engine as the active subset of
 * `vendors` (status='active'). The engine never queries the DB itself.
 */
export interface VendorCatalogueEntry {
  id: string;
  slug: string;
  category: string;
  currentVersionId: string | null;
  category_label: string;
  targetHotelSizes: string[];
  targetPropertyTypes: string[];
  countriesServed: string[];
  languagesSupported: string[];
  independentHotelSuitability: string | null;
  smallHotelSuitability: string | null;
  implementationComplexity: string | null;
  priceTier: string | null;
  frenchMarketRelevance: string | null;
  gdprPosture: string | null;
  euHosting: string | null;
  aiFeatures: string[];
  automationCapabilities: string[];
  tags: string[];
  confidence: string;
}

export interface HotelSnapshot {
  property_type: string | null;
  room_count: number | null;
  country: string | null;
  region: string | null;
  city: string | null;
  primary_language: string;
  star_rating: number | null;
}

export interface ProjectSnapshot {
  id: string;
  tier: string;
  goal_primary: string | null;
  goal_secondary: string[];
  budget_level: string | null;
}

export interface AnswerInput {
  question_slug: string;
  question_version_id: string | null;
  value: unknown;
  source: string;
  confidence: string;
}

export interface ScanFindingInput {
  field: string;
  value: unknown;
  confidence: string;
}

export interface RecommendationContext {
  project: ProjectSnapshot;
  hotel: HotelSnapshot;
  answers: AnswerInput[];
  /** Convenience lookup map answers[slug] = value. */
  answersByslug: Record<string, unknown>;
  /** Confidence per answer slug (low signals weaker downstream reasoning). */
  answerConfidence: Record<string, string>;
  scanFindings: ScanFindingInput[];
  scanByField: Record<string, unknown>;
  vendorCatalogue: VendorCatalogueEntry[];
}

/* ------------------------------ Outputs ------------------------------ */

export type Band = "low" | "medium" | "high";
export type Severity = "info" | "advisory" | "risk";

export interface SignalsConsulted {
  answers: string[];
  scan_findings: string[];
  vendor_fields: string[];
}

export interface ExplanationShape {
  relevance: string;
  problem_solved: string;
  change: string;
  benefit: string;
  effort: string;
  risks: string;
  check_before: string;
  alternatives: string[];
  do_nothing_consequence: string;
}

export interface ImpactShape {
  operational: Band;
  workload_reduction: Band;
  guest_experience: Band;
  response_speed: Band;
  consistency: Band;
  onboarding: Band;
  direct_booking: Band;
  complexity: Band;
  cost_band: string;
  time_to_deploy: "immediate" | "30d" | "60d" | "90d" | "quarter_plus";
  risk_level: Band;
  dependencies: string[];
  confidence: Band;
}

export interface EligibleVendor {
  vendor: VendorCatalogueEntry;
  reasons: string[];
  signals: SignalsConsulted;
}

export interface RuleRecommendation {
  /** Stable client-side id (uuid generated by engine). */
  id: string;
  action: string;
  scenario_kind: ScenarioKind | "standalone";
  vendor_id: string | null;
  vendor_version_id: string | null;
  vendor_name: string | null;
  vendor_category: string | null;
  explanation: ExplanationShape;
  impact: ImpactShape;
  confidence: Band;
  do_not_do_now: boolean;
  do_not_do_reason: string | null;
  signals_consulted: SignalsConsulted;
  /** Source rule id; helps debugging + future deduplication. */
  rule_id: string;
  /** Sort key inside its roadmap bucket. */
  priority: number;
  /** Implementation effort / impact (drives roadmap bucketing). */
  expected_effort: Band;
  expected_impact: Band;
  /** Optional roadmap dependencies (other recommendation ids). */
  dependencies: string[];
  recommended_owner: "hotelier" | "consultant" | "external" | "shared";
}

export interface RuleScenario {
  id: string;
  kind: ScenarioKind;
  title: string;
  summary: string;
  tradeoffs: Record<string, string>;
  recommendation_ids: string[];
}

export interface ReadinessScoreResult {
  dimension: ScoreDimension;
  value: number; // 0..100
  band: Band;
  basis: string[]; // FR-037: enumerated answer/finding ids
}

export interface ComplianceFinding {
  topic: string;
  severity: Severity;
  explanation: string;
  checklist_item: string;
  vendor_id: string | null;
}

export interface OpportunityMapEntry {
  category: string;
  headline: string;
  detail?: string;
  severity: "info" | "opportunity" | "risk";
}

export interface BottleneckEntry {
  bottleneck: string;
  description: string;
  evidence: string[];
}

export interface ToolStackOverview {
  current: { category: string; vendor: string | null; confidence: string }[];
  missing: string[];
  redundant: string[];
}

export interface RoadmapItemOutput {
  recommendation_id: string;
  bucket: "immediate" | "30d" | "60d" | "90d" | "postponed" | "not_now";
  expected_effort: Band;
  expected_impact: Band;
  dependencies: string[];
  recommended_owner: "hotelier" | "consultant" | "external" | "shared";
  implementation_risk: Band;
  decision_points: Array<{ when: string; question: string; resolution_options: string[] }>;
}

export interface EngineOutput {
  executive_summary: string;
  scenarios: RuleScenario[];
  recommendations: RuleRecommendation[];
  readiness_scores: ReadinessScoreResult[];
  compliance_findings: ComplianceFinding[];
  opportunity_map: OpportunityMapEntry[];
  bottleneck_analysis: BottleneckEntry[];
  tool_stack_overview: ToolStackOverview;
  roadmap_items: RoadmapItemOutput[];
  next_steps: string[];
  rule_engine_version: string;
  referenced_vendor_version_ids: string[];
}
